[blocks.width.wallpaper]
candidates = ["768"]

[blocks.height.wallpaper]
candidates = ["432"]

[blocks.prompt.base]
candidates = [
    "Ford Mustang",
    "Porsche 911",
]

[blocks.prompt.model]
candidates = [
    "[1970 | 1980 | 1990 | 2000 | 2010 | 2020] model",
]

[blocks.prompt.color]
weighting = "keyword"
candidates = [
    "[blue | red | mustard] paint job",
]

[blocks.prompt.scene]
candidates = [
    "on the (busy) highway",
    "in the desert",
    "(drifting) on a racing track",
    "in the streets of [Paris | New York]",
]

[blocks.prompt.lightning]
optional = true
weighting = "keyword"
candidates = [
    "[smooth | soft | ambient] lightning",
    "direct sunlight",
    "moonlight:0.8",
]

[blocks.prompt.image-details]
candidates = [
    "realistic",
    "highly detailed",
    "photography",
    "masterpiece",
]

[blocks.prompt.camera-view]
optional = true
weighting = "keyword"
candidates = [
    "[low | wide | ultra-wide] angle",
]
