name: 'testing'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  latest:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-latest"]
            python-version: ["3.10", "3.11"]
            include:
              - os: "ubuntu-latest"
                os-name: "Ubuntu"
              - python-version: "3.11"
              - python-version: "3.10"
    name: ${{ matrix.os-name }} with Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
        name: 'Setup python'
      - shell: bash
        run: python install.py
        name: 'Install standard dependencies'
      - shell: bash
        run: python -m pip install pytest
        name: 'Install testing dependencies'
      - shell: bash
        run: pytest
        name: 'Run tests'
